[package]
name = "conventional"
version = "0.5.0"
authors = ["Jean Mertz <helloworld@rustic.games>"]
keywords = ["parser", "git", "conventional-commit", "commit", "conventional"]
categories = ["parser-implementations"]
description = "A parser library for the Conventional Commit specification."
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/rustic-games/conventional-commit"
edition = "2018"

[dependencies]
nom = { version = "5", default-features = false, features = ["std"] }
unicase = "2.5"

[dev-dependencies]
indoc = "0.3"
